def COLOR_MAP = ['SUCCESS': 'good', 'FAILURE': 'danger', 'UNSTABLE': 'danger', 'ABORTED': 'danger']

@NonCPS
def getChangeString() {
    MAX_MSG_LEN = 100
    def changeString = ""
    echo "Gathering SCM changes"
    def changeLogSets = currentBuild.rawBuild.changeSets
    for (int i = 0; i < changeLogSets.size(); i++) {
        def entries = changeLogSets[i].items
        for (int j = 0; j < entries.length; j++) {
            def entry = entries[j]
            truncated_msg = entry.msg.take(MAX_MSG_LEN)
            changeString += " - ${truncated_msg} [${entry.author}]\n"
        }
    }
    if (!changeString) {
        changeString = " - No new changes"
    }
    return changeString
}

pipeline {
    agent any

    environment {
        DOCKER_REGISTRY_URL = 'https://docker-reg.your-company.com'
        DOCKER_REGISTRY_USERNAME = credentials('DOCKER_REGISTRY_USERNAME')
        DOCKER_REGISTRY_PW = credentials('DOCKER_REGISTRY_PW')

        SERVER_USERNAME = credentials('YOUR_PROJECT_API_SERVER_USERNAME')
        SERVER_URL_DEV = credentials('YOUR_PROJECT_API_SERVER_URL_DEV')
        SERVER_URL_TEST = credentials('YOUR_PROJECT_API_SERVER_URL_TEST')
        SERVER_URL_PRODUCTION = credentials('YOUR_PROJECT_API_SERVER_URL_PRODUCTION')
        SERVER_SSH_KEY_FILE_DEV = credentials('YOUR_PROJECT_API_SERVER_SSH_KEY_FILE_DEV')
        SERVER_SSH_KEY_FILE_TEST = credentials('YOUR_PROJECT_API_SERVER_SSH_KEY_FILE_TEST')
        SERVER_SSH_KEY_FILE_PRODUCTION = credentials('YOUR_PROJECT_API_SERVER_SSH_KEY_FILE_PRODUCTION')

        ENV_DEV = credentials('YOUR_PROJECT_API_ENV_DEV')
        ENV_TEST = credentials('YOUR_PROJECT_API_ENV_TEST')
        ENV_PRODUCTION = credentials('YOUR_PROJECT_API_ENV_PRODUCTION')
        
        APP_URL_DEV = credentials('YOUR_PROJECT_API_APP_URL_DEV')
        APP_URL_TEST = credentials('YOUR_PROJECT_API_APP_URL_TEST')
        APP_URL_PRODUCTION = credentials('YOUR_PROJECT_API_APP_URL_PRODUCTION')
    }

    options {
        disableConcurrentBuilds()
    }

    stages {
        // Select environment
        // Dev Environment
        stage('Use Dev Env') {
            when {
                branch 'dev'
            }
            steps {
                script {
                    env.TAG = 'dev'
                    env.ENV_FILE = "${env.ENV_DEV}"
                    env.SERVER_URL = "${env.SERVER_URL_DEV}"
                    env.SERVER_SSH_KEY_FILE = "${env.SERVER_SSH_KEY_FILE_DEV}"
                    env.APP_URL = "${env.APP_URL_DEV}"
                }

                echo "BUILD_ENV: dev"
                echo "TAG: $TAG"
            }
        }
        // -- Test Environment
        stage('Use Test Env') {
            when {
                branch 'test'
            }
            steps {
                script {
                    env.TAG = 'test'
                    env.ENV_FILE = "${env.ENV_TEST}"
                    env.SERVER_URL = "${env.SERVER_URL_TEST}"
                    env.SERVER_SSH_KEY_FILE = "${env.SERVER_SSH_KEY_FILE_TEST}"
                    env.APP_URL = "${env.APP_URL_TEST}"
                }

                echo "BUILD_ENV: test"
                echo "TAG: $TAG"
            }
        }
        // -- Production Environment
        stage('Use Production Env') {
            when {
                branch 'master'
            }
            steps {
                script {
                    env.TAG = 'production'
                    env.ENV_FILE = "${env.ENV_PRODUCTION}"
                    env.SERVER_URL = "${env.SERVER_URL_PRODUCTION}"
                    env.SERVER_SSH_KEY_FILE = "${env.SERVER_SSH_KEY_FILE_PRODUCTION}"
                    env.APP_URL = "${env.APP_URL_PRODUCTION}"
                }

                echo "BUILD_ENV: production"
                echo "TAG: $TAG"
            }
        }
        // Build
        stage('Build') {
            when {
                expression {
                    return env.DISABLE_BUILD_STEP != 'true';
                }
            }
            parallel {
                stage('Build App') {
                    steps {
                      sh 'chmod +x ./jenkins/scripts/build.sh && ./jenkins/scripts/build.sh'
                    }
                }
            }
        }
        // Deploy
        stage('Deploy') {
            when {
                anyOf {
                    branch 'master'
                    branch 'test'
                    branch 'dev'
                }
            }

            steps {
                sh 'chmod +x ./jenkins/scripts/deploy.sh && ./jenkins/scripts/deploy.sh'
            }
        }
        stage('Cleanup') {
            steps {
                // sh 'chmod +x ./jenkins/scripts/cleanup.sh && ./jenkins/scripts/cleanup.sh'
                echo 'skip clean atm'
            }
        }
    }

    post {
        always {
            rocketSend channel: '#DP_Your Project_Deploy_Notification',
                color: COLOR_MAP[currentBuild.currentResult],
                message: "`Your Project API (${TAG})` - *${currentBuild.currentResult}*\n    Job ${JOB_NAME} build ${BUILD_NUMBER}\n    ${BUILD_URL}\n    ${APP_URL}\n    Changes: \n$changeString"
        }
    }
}
