name: Node.js CI

on:
  push:
    branches:
      - test-branch # change to "dev" or smth else

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: Install npm dependencies
        run: npm install --legacy-peer-deps

      - name: Prisma Client Generate
        run: npx prisma generate

      - name: Run build task
        run: npm run build

      - name: Run lint
        run: npm run lint
